modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "All Rights Reserved"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/ftb-ez-crystals"
#logoFile = "logo.png"
authors = "Mrbysco, FTB Team"
description = '''
FTB Ez Crystals is a lightweight quality-of-life mod that allows players to right-click budding amethyst blocks to instantly harvest a full amethyst cluster without breaking the block or waiting for growth stages. Designed for seamless integration and automation support, this mod simplifies crystal farming mechanics with minimal performance impact.
'''

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "${loader_version_range}"
ordering = "NONE"
side="BOTH"
